site_name: Jonh09'sGuides
theme: 
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  language: en
  palette:
    - scheme: default

    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode
    - scheme: slate 
      accent: deep purple

nav:
  - About: index.md
  - Overall Guides: guides\mods\introduction.md
  - ATM9 Guides: guides\atm9\introduction.md
  - ATM10 Guides: guides\atm10\introduction.md
extra:
  social:
    - icon: fontawesome/brands/discord
      link: https://discord.com/invite/allthemods
      name: Find me in the AllTheMods discord - @Jonh09
      

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - attr_list



copyright: |
  &copy; 2024 <a href="https://github.com/Jmpp2909"  target="_blank" rel="noopener">Jmpp2909 aka Jonh09</a>